Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$sharedRoot = Join-Path $repoRoot "shared"
$backendRoot = Join-Path $repoRoot "backends"
$surfaceRoot = Join-Path $repoRoot "surfaces"
$platformRoot = Join-Path $repoRoot "platform"

function Get-SurfaceManifest {
    param([Parameter(Mandatory = $true)][string]$Path)

    return (Get-Content -Raw -LiteralPath $Path | ConvertFrom-Json)
}

function Get-SurfaceManifests {
    return @(
        Get-ChildItem -Path $surfaceRoot -Filter "surface.json" -Recurse -File |
            Sort-Object FullName |
            ForEach-Object { Get-SurfaceManifest -Path $_.FullName }
    )
}

function Get-BackendManifest {
    param([Parameter(Mandatory = $true)][string]$BackendId)

    $manifestPath = Join-Path $backendRoot "$BackendId\backend.json"
    if (-not (Test-Path -LiteralPath $manifestPath)) {
        throw "Backend manifest not found for '$BackendId': $manifestPath"
    }

    return (Get-Content -Raw -LiteralPath $manifestPath | ConvertFrom-Json)
}

function Resolve-RepoRelativePath {
    param([Parameter(Mandatory = $true)][string]$RelativePath)

    return (Join-Path $repoRoot $RelativePath)
}

function Get-SurfacePackageRoot {
    param([Parameter(Mandatory = $true)]$Surface)

    if ([string]$Surface.package_root -eq ".") {
        return $repoRoot.Path
    }

    return (Join-Path $repoRoot ([string]$Surface.package_root))
}

function Ensure-Directory {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType Directory -Path $Path | Out-Null
    }
}

function Copy-File {
    param(
        [Parameter(Mandatory = $true)][string]$SourcePath,
        [Parameter(Mandatory = $true)][string]$DestinationPath
    )

    $resolvedSourcePath = (Resolve-Path -LiteralPath $SourcePath).Path
    $sourceComparisonPath = [System.IO.Path]::GetFullPath($resolvedSourcePath)
    $destinationComparisonPath = [System.IO.Path]::GetFullPath($DestinationPath)

    if ($sourceComparisonPath -eq $destinationComparisonPath) {
        return
    }

    Ensure-Directory -Path (Split-Path -Parent $DestinationPath)
    Copy-Item -LiteralPath $resolvedSourcePath -Destination $DestinationPath -Force
}

function Get-GeneratedSkillMarkdown {
    param([Parameter(Mandatory = $true)]$Surface)

    $workflow = Get-Content -Raw -LiteralPath (Join-Path $sharedRoot "docs\workflow.md")
    $review = Get-Content -Raw -LiteralPath (Join-Path $sharedRoot "docs\review-checklist.md")
    $promptTemplate = Get-Content -Raw -LiteralPath (Join-Path $sharedRoot "docs\prompt-template.md")
    $backendNotes = Get-Content -Raw -LiteralPath (Join-Path $backendRoot "$($Surface.notes_backend)\skill-backend.md")

    @"
---
name: $($Surface.package_name)
description: $($Surface.description)
---

# $($Surface.display_name)

This file is generated by scripts/build-packages.ps1. Edit shared content under shared/ and backend-specific content under backends/.

$workflow

$backendNotes

$promptTemplate

$review
"@
}

function Get-GeneratedOpenAiYaml {
    param([Parameter(Mandatory = $true)]$Surface)

    @"
interface:
  display_name: "$($Surface.display_name)"
  short_description: "$($Surface.short_description)"
  default_prompt: "$($Surface.default_prompt)"
"@
}

function Write-PackageFiles {
    param([Parameter(Mandatory = $true)]$Surface)

    $packageRoot = Get-SurfacePackageRoot -Surface $Surface
    Ensure-Directory -Path (Join-Path $packageRoot "agents")

    Set-Content -LiteralPath (Join-Path $packageRoot "SKILL.md") `
        -Value (Get-GeneratedSkillMarkdown -Surface $Surface) `
        -NoNewline
    Set-Content -LiteralPath (Join-Path $packageRoot "agents\openai.yaml") `
        -Value (Get-GeneratedOpenAiYaml -Surface $Surface) `
        -NoNewline
}

function Sync-SharedModule {
    param([Parameter(Mandatory = $true)][string]$DestinationPackageRoot)

    Copy-File `
        -SourcePath (Join-Path $sharedRoot "scripts\DelegateCommon.psm1") `
        -DestinationPath (Join-Path $DestinationPackageRoot "shared\scripts\DelegateCommon.psm1")
}

function Sync-PlatformRuntime {
    param([Parameter(Mandatory = $true)][string]$DestinationPackageRoot)

    $runtimeSourceRoot = Join-Path $platformRoot "runtime"
    foreach ($runtimeFile in Get-ChildItem -Path $runtimeSourceRoot -Recurse -File) {
        $relativePath = [System.IO.Path]::GetRelativePath($runtimeSourceRoot, $runtimeFile.FullName)
        Copy-File `
            -SourcePath $runtimeFile.FullName `
            -DestinationPath (Join-Path $DestinationPackageRoot "platform\runtime\$relativePath")
    }
}

function Sync-RegistryManifests {
    param([Parameter(Mandatory = $true)][string]$DestinationPackageRoot)

    foreach ($backendManifest in Get-ChildItem -Path $backendRoot -Filter "backend.json" -Recurse -File) {
        $backendId = Split-Path -Leaf (Split-Path -Parent $backendManifest.FullName)
        Copy-File `
            -SourcePath $backendManifest.FullName `
            -DestinationPath (Join-Path $DestinationPackageRoot "registry\backends\$backendId\backend.json")

        $defaultConfigPath = Join-Path $backendManifest.Directory.FullName "backend.defaults.json"
        if (Test-Path -LiteralPath $defaultConfigPath) {
            Copy-File `
                -SourcePath $defaultConfigPath `
                -DestinationPath (Join-Path $DestinationPackageRoot "registry\backends\$backendId\backend.defaults.json")
        }
    }

    foreach ($surfaceManifest in Get-ChildItem -Path $surfaceRoot -Filter "surface.json" -Recurse -File) {
        $surfaceId = Split-Path -Leaf (Split-Path -Parent $surfaceManifest.FullName)
        Copy-File `
            -SourcePath $surfaceManifest.FullName `
            -DestinationPath (Join-Path $DestinationPackageRoot "registry\surfaces\$surfaceId\surface.json")
    }
}

function Get-BackendRunnerSourcePath {
    param([Parameter(Mandatory = $true)][string]$BackendId)

    $manifest = Get-BackendManifest -BackendId $BackendId
    return (Resolve-RepoRelativePath -RelativePath ([string]$manifest.runner_script))
}

function Get-BackendRunnerDestinationPath {
    param(
        [Parameter(Mandatory = $true)][string]$DestinationPackageRoot,
        [Parameter(Mandatory = $true)][string]$BackendId
    )

    return (Join-Path $DestinationPackageRoot ("scripts\run_{0}_delegate.ps1" -f $BackendId))
}

function Sync-BackendRunnersForSurface {
    param([Parameter(Mandatory = $true)]$Surface)

    $packageRoot = Get-SurfacePackageRoot -Surface $Surface
    $backendIds = switch ([string]$Surface.mode) {
        "single-backend" { @([string]$Surface.default_backend) }
        "router" { @($Surface.allowed_backends | ForEach-Object { [string]$_ }) }
        default { throw "Unsupported surface mode '$($Surface.mode)' for surface '$($Surface.id)'." }
    }

    foreach ($backendId in $backendIds) {
        Copy-File `
            -SourcePath (Get-BackendRunnerSourcePath -BackendId $backendId) `
            -DestinationPath (Get-BackendRunnerDestinationPath -DestinationPackageRoot $packageRoot -BackendId $backendId)
    }
}

function Sync-SurfacePublicScripts {
    param([Parameter(Mandatory = $true)]$Surface)

    $packageRoot = Get-SurfacePackageRoot -Surface $Surface
    foreach ($scriptRelativePath in @($Surface.public_scripts)) {
        Copy-File `
            -SourcePath (Resolve-RepoRelativePath -RelativePath ([string]$scriptRelativePath)) `
            -DestinationPath (Join-Path $packageRoot ("scripts\" + [System.IO.Path]::GetFileName([string]$scriptRelativePath)))
    }
}

function Sync-SurfacePublicAssets {
    param([Parameter(Mandatory = $true)]$Surface)

    $packageRoot = Get-SurfacePackageRoot -Surface $Surface
    foreach ($asset in @($Surface.public_assets)) {
        Copy-File `
            -SourcePath (Resolve-RepoRelativePath -RelativePath ([string]$asset.source)) `
            -DestinationPath (Join-Path $packageRoot ([string]$asset.target))
    }
}

foreach ($surface in @(Get-SurfaceManifests)) {
    $packageRoot = Get-SurfacePackageRoot -Surface $surface
    Ensure-Directory -Path $packageRoot

    Write-PackageFiles -Surface $surface

    if ([string]$surface.package_root -ne ".") {
        Sync-SharedModule -DestinationPackageRoot $packageRoot
    }

    if ([string]$surface.mode -eq "router") {
        Sync-PlatformRuntime -DestinationPackageRoot $packageRoot
        Sync-RegistryManifests -DestinationPackageRoot $packageRoot
    }

    Sync-BackendRunnersForSurface -Surface $surface
    Sync-SurfacePublicScripts -Surface $surface
    Sync-SurfacePublicAssets -Surface $surface

    Write-Host "Generated surface package: $($surface.id)"
}
