Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$sharedRoot = Join-Path $repoRoot "shared"
$backendRoot = Join-Path $repoRoot "backends"
$packageRoot = Join-Path $repoRoot "packages"
$opencodePackageRoot = Join-Path $packageRoot "codex-delegate-opencode"
$agentPackageRoot = Join-Path $packageRoot "codex-delegate-agent"

function Get-BackendMetadata {
    param([Parameter(Mandatory = $true)][string]$Backend)

    $metadataPath = Join-Path $backendRoot "$Backend\agent.json"
    Get-Content -Raw -LiteralPath $metadataPath | ConvertFrom-Json
}

function Get-GeneratedSkillMarkdown {
    param([Parameter(Mandatory = $true)]$Metadata, [Parameter(Mandatory = $true)][string]$Backend)

    $workflow = Get-Content -Raw -LiteralPath (Join-Path $sharedRoot "docs\workflow.md")
    $review = Get-Content -Raw -LiteralPath (Join-Path $sharedRoot "docs\review-checklist.md")
    $promptTemplate = Get-Content -Raw -LiteralPath (Join-Path $sharedRoot "docs\prompt-template.md")
    $backendNotes = Get-Content -Raw -LiteralPath (Join-Path $backendRoot "$Backend\skill-backend.md")

    @"
---
name: $($Metadata.name)
description: $($Metadata.description)
---

# $($Metadata.displayName)

This file is generated by scripts/build-packages.ps1. Edit shared content under shared/ and backend-specific content under backends/.

$workflow

$backendNotes

$promptTemplate

$review
"@
}

function Get-GeneratedOpenAiYaml {
    param([Parameter(Mandatory = $true)]$Metadata)

    @"
interface:
  display_name: "$($Metadata.displayName)"
  short_description: "$($Metadata.shortDescription)"
  default_prompt: "$($Metadata.defaultPrompt)"
"@
}

function Ensure-Directory {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType Directory -Path $Path | Out-Null
    }
}

function Sync-SharedModule {
    param([Parameter(Mandatory = $true)][string]$DestinationPackageRoot)

    $destinationSharedScripts = Join-Path $DestinationPackageRoot "shared\scripts"
    Ensure-Directory -Path $destinationSharedScripts
    Copy-Item -LiteralPath (Join-Path $sharedRoot "scripts\DelegateCommon.psm1") `
        -Destination (Join-Path $destinationSharedScripts "DelegateCommon.psm1") `
        -Force
}

function Copy-BackendScript {
    param(
        [Parameter(Mandatory = $true)][string]$SourcePath,
        [Parameter(Mandatory = $true)][string]$DestinationPath
    )

    Ensure-Directory -Path (Split-Path -Parent $DestinationPath)
    Copy-Item -LiteralPath $SourcePath -Destination $DestinationPath -Force
}

function Write-PackageFiles {
    param(
        [Parameter(Mandatory = $true)][string]$Backend,
        [Parameter(Mandatory = $true)][string]$SkillRoot
    )

    $metadata = Get-BackendMetadata -Backend $Backend
    Ensure-Directory -Path (Join-Path $SkillRoot "agents")
    $skillPath = Join-Path $SkillRoot "SKILL.md"
    $agentPath = Join-Path $SkillRoot "agents\openai.yaml"

    Set-Content -LiteralPath $skillPath -Value (Get-GeneratedSkillMarkdown -Metadata $metadata -Backend $Backend) -NoNewline
    Set-Content -LiteralPath $agentPath -Value (Get-GeneratedOpenAiYaml -Metadata $metadata) -NoNewline
}

Ensure-Directory -Path $packageRoot
Ensure-Directory -Path (Join-Path $opencodePackageRoot "scripts")
Ensure-Directory -Path (Join-Path $opencodePackageRoot "agents")
Ensure-Directory -Path (Join-Path $agentPackageRoot "scripts")
Ensure-Directory -Path (Join-Path $agentPackageRoot "agents")

Write-PackageFiles -Backend "claude" -SkillRoot $repoRoot
Write-PackageFiles -Backend "opencode" -SkillRoot $opencodePackageRoot
Write-PackageFiles -Backend "agent" -SkillRoot $agentPackageRoot
Sync-SharedModule -DestinationPackageRoot $opencodePackageRoot
Sync-SharedModule -DestinationPackageRoot $agentPackageRoot
Copy-BackendScript `
    -SourcePath (Join-Path $backendRoot "opencode\run_opencode_delegate.ps1") `
    -DestinationPath (Join-Path $opencodePackageRoot "scripts\run_opencode_delegate.ps1")
Copy-BackendScript `
    -SourcePath (Join-Path $backendRoot "agent\run_delegate_agent.ps1") `
    -DestinationPath (Join-Path $agentPackageRoot "scripts\run_delegate_agent.ps1")
Copy-BackendScript `
    -SourcePath (Join-Path $repoRoot "scripts\run_claude_delegate.ps1") `
    -DestinationPath (Join-Path $agentPackageRoot "scripts\run_claude_delegate.ps1")
Copy-BackendScript `
    -SourcePath (Join-Path $backendRoot "opencode\run_opencode_delegate.ps1") `
    -DestinationPath (Join-Path $agentPackageRoot "scripts\run_opencode_delegate.ps1")

Write-Host "Generated root Claude package metadata."
Write-Host "Generated OpenCode package metadata."
Write-Host "Generated unified agent package metadata."
Write-Host "Synced shared module into generated packages."
